### ISSUE TITLE
Is it possible to add markdown header levels #, ##, ### as a swaplist

### ISSUE THREAD

**Issue by kiryph** [mjbrownie/swapit#27]
I had another idea for a swaplist for markdown files:

I have tried two definitions in `~/.vim/after/ftplugin/markdown_swapit.vim`:

1.
```
SwapList formats # ## ###
```
2.
```
let g:swap_lists = [
        \{'name':'formats', 'options':
        \['#','##' , '###']},
        \]
```
Unfortunately, both do not work. Why?

**Comment by mjbrownie** [comment]
Hi, I'm afraid it wont work as is. (It might work in visual mode) I originally wrote the command to match on the :he <cword> register. 

1. Matches the <cword> from your lists
2. Performs what amounts to a viwp (visual-inner-word-paste) in ProcessMatches()

Note that <cword> is limited to alphanumeric. There is code to handle visual mode selections but it is a bit clunky.

So it is not good for non alpha lists like ( || && ) etc, which would be handy. 

I think there have since been some other substitution scripts that might handle this (cycle.vim?) but I haven't looked at them.

I looked at changing the <cword> hack to something more general purpose but it's probably better off being rewritten in something like python.

You could also take advantage of the SwapitFallback(incrementor,Decrimentor) and write your own function. You would probably only need a few substitutes s/^#/##/ s/^##/###  etc.

**Comment by kiryph** [comment]
Thanks for your reply.

Maybe you can add the information to the documentation of `swapit` that only alphanumeric keywords are allowed.

Indeed you were right that other plugins could handle non-alphanumeric letters. I have checked additional features I like:

| Plugin | dot-repeat | Forward to speeddating <br> and builtin inc/dec | non-alphanum keywords |
| --- | --- | --- | --- |
| [swapit](https://github.com/mjbrownie/swapit/) | yes | yes | no |
| [bootleq/vimcycle](https://github.com/bootleq/vim-cycle) |yes | yes | yes |
| [zef/vim-cycle](https://github.com/zef/vim-cycle) | no | no | yes |
| [toggle.vim](http://www.vim.org/scripts/script.php?script_id=895) | only toggle <br> no inc/dec | no | yes |

I guess I will give `bootleq/vimcycle` a shot.

**Comment by kiryph** [comment]
Another note regarding incrementing/decrementing markdown header levels:

The plugin https://github.com/plasticboy/vim-markdown provides the functions `:HeaderIncrease` and `:HeaderDecrease`. However, I am not sure whether they can chained into `ctrl-a/x` as done with speeddating.
